// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0tq-tbdL-D_o_NwG-fGBmp9R15zmmCfg',
    appId: '1:722569510491:web:3a93e7e0551f41e8fdc97e',
    messagingSenderId: '722569510491',
    projectId: 'climb-balance',
    authDomain: 'climb-balance.firebaseapp.com',
    storageBucket: 'climb-balance.appspot.com',
    measurementId: 'G-TLZN4WZ7TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtgPCazwwuZD_dFt6YLWtZOlkdFwauBRE',
    appId: '1:722569510491:android:fbb5692e75f122d8fdc97e',
    messagingSenderId: '722569510491',
    projectId: 'climb-balance',
    storageBucket: 'climb-balance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGNt2WkLPPLeEBWgV7l4Cz0q6xBKzx9B8',
    appId: '1:722569510491:ios:1e8dbbd2c503a89dfdc97e',
    messagingSenderId: '722569510491',
    projectId: 'climb-balance',
    storageBucket: 'climb-balance.appspot.com',
    iosClientId: '722569510491-pfo8bede8np171m7b0u78m7992959nu2.apps.googleusercontent.com',
    iosBundleId: 'com.climbbalance.climbBalance',
  );
}
